# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: terraform-provider-onepassword

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-onepassword
    main: ./main.go
    binary: '{{ .ProjectName }}_v{{.Version}}'
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -extldflags '-static'"
    # Environment variables overrides for the cross-compiler
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc

archives:
  - formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # draft: true # uncomment this to create a draft release
changelog:
  disable: true