# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: terraform-provider-onepassword

before:
  hooks:
    - go mod tidy

builds:
  - id: provider
    main: ./main.go
    binary: terraform-provider-onepassword
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - formats: ["zip", "tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  disable: false